name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install pytest numpy
    - name: Lab 9 Validation
      id: lab-9-validation
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Lab 9 Validation
        command: pytest test_lab_9.py -v
        timeout: 120
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LAB-9-VALIDATION_RESULTS: "${{steps.lab-9-validation.outputs.result}}"
      with:
        runners: lab-9-validation
